name: publish

on:
  push:
    branches: 
    - staging
    - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'version'
      id: version
      shell: bash
      run: |
        branchName="${GITHUB_REF#refs/heads/}"
        echo "$branchName"
        echo "::set-output name=BRANCH_NAME::$branchName"
          
    - name: 'copy branch files'
      shell: bash
      run: |
        cp -r content/${{ steps.version.outputs.BRANCH_NAME }} content/copy
          
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.SP_CLIENTID }}
        password: ${{ secrets.SP_CLIENTSECRET }}
    - run: |
        docker build --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/mvpdaysrsa:${{ github.sha }} --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/mvpdaysrsa:${{ steps.version.outputs.BRANCH_NAME }} -f src/Dockerfile .
        docker push --all-tags ${{ secrets.REGISTRY_LOGIN_SERVER }}/mvpdaysrsa
        
    - name: 'Deploy to Azure Web App (staging)'
      if: ${{ steps.version.outputs.BRANCH_NAME == 'staging' }}
      id: deploy-to-webapp-staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ steps.version.outputs.BRANCH_NAME }}-mvpdaysrsa'
        slot-name: 'production'
        publish-profile: ${{ secrets.PUBLISHPROFILE_STAGING }}
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/mvpdaysrsa:${{ github.sha }}'

    - name: 'Deploy to Azure Web App (main)'
      if: ${{ steps.version.outputs.BRANCH_NAME == 'main' }}
      id: deploy-to-webapp-main
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ steps.version.outputs.BRANCH_NAME }}-mvpdaysrsa'
        slot-name: 'production'
        publish-profile: ${{ secrets.PUBLISHPROFILE_MAIN }}
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/mvpdaysrsa:${{ github.sha }}'

    - name: Azure logout
      run: |
        az logout
        
